### ISSUE TITLE
将文件从一个存储复制到另一个存储

### ISSUE THREAD

**Issue by ghost** [Dawnnnnnn/Alist-Encrypt-Module#1]
测试：将文件(视频、图片)从本地存储(未加密的文件夹)复制到天翼云盘(加密的文件夹)。
将文件从未加密的存储复制到加密的存储，文件无法在线浏览，而官方客户端可以正常在线浏览。

**Comment by Dawnnnnnn** [comment]
与模块无关，请去加密项目作者处反馈
